### ISSUE TITLE
Remove or update Code of Conduct

### ISSUE THREAD

**Issue by jpower432** [oscal-compass/compliance-to-policy#24]
### Issue description
The Code of Conduct has been updated in the community repository. CoC reporting will now go to a shared email. The Code of Conduct in this repository is pointing to the `compliance-trestle` repository which is now resulting in a 404.

### Caveats / Assumptions
Related to https://github.com/oscal-compass/compliance-trestle/issues/1589

### Completion Criteria
Update the CoC to point to - https://github.com/oscal-compass/community/blob/main/CODE_OF_CONDUCT.md
OR Remove the CoC and inherit from the organization level configuration

**Comment by yana1205** [comment]
Hi @jpower432,

Could you please review and approve the PR (#25)?

**Comment by yana1205** [comment]
Thank you!
